### ISSUE TITLE
SPARQL 1.2 WC3 Community Group

### ISSUE THREAD

**Issue by ktk** [eBay/beam#18]
Hi everyone,

Great to see your work with beam, looks very interesting and we are really interested in the discussions you are having about aligning with RDF/SPARQL. I'm referring to [this](https://github.com/eBay/beam/blob/master/docs/query.md) document for example. I think you might be a valuable contributor to a W3C Community Group we [just recently launched](https://twitter.com/AndySeaborne/status/1111636564239679489) after a [meetup in Berlin](https://twitter.com/linkedktk/status/1103327510144712704) in February. It's about defining what could become SPARQL 1.2 and later maybe 2.0.

This is a W3C Community Group, which is much less formal and more open than a formal W3C group to release a standard. The ones driving it right now are all people that work with SPARQL for many years and some of them implement it as well, so it is very hands-on.

We are interested in making SPARQL easier to use and add stuff many of us are missing right now. Having people like you involved sounds like a great extension to a possible new standard in the future.

Feel free to close this issue immediately, I just wanted to make sure that you are aware of what is going on there.

You can find a list of collected ideas so far in the [GitHub](https://github.com/w3c/sparql-12/issues) repository.

**Comment by superfell** [comment]
Thanks for reaching out, I'll take a look.
