### ISSUE TITLE
Can't see how to resolve views.proto for Ubuntu 18.04

### ISSUE THREAD

**Issue by fils** [eBay/beam#26]
Very excited to try this....

However, I can't seem to get past some of the dependencies for Ubuntu 18.04

not sure where to resolve "views.proto"

```
go install vendor/golang.org/x/tools/cmd/goimports
go install vendor/honnef.co/go/tools/cmd/staticcheck
PATH=/home/fils/src/git/beam/bin:/home/fils/.cargo/bin:/home/fils/bin:/home/fils/.cargo/bin:/home/fils/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-10-oracle/bin:/usr/lib/jvm/java-10-oracle/db/bin:/usr/local/go/bin:/usr/local/go/bin:/home/fils/src/go/bin:/home/fils/.cargo/bin:/home/fils/src/flutter/bin:/home/fils/.local/bin:/usr/local/android-studio/bin:/usr/lib/dart/bin:/home/fils/.pub-cache/bin:/usr/lib/jvm/java-10-oracle/bin:/usr/lib/jvm/java-10-oracle/db/bin:/usr/local/go/bin:/usr/local/go/bin:/home/fils/src/go/bin:/home/fils/.cargo/bin:/home/fils/src/flutter/bin:/home/fils/.local/bin:/usr/local/android-studio/bin:/usr/lib/dart/bin:/home/fils/.pub-cache/bin protoc --gogoslick_out=plugins=grpc:src/github.com/ebay/beam/rpc -Isrc:src/vendor:src/github.com/ebay/beam/rpc views.proto
views.proto: No such file or directory
Makefile:54: recipe for target 'src/github.com/ebay/beam/rpc/views.pb.go' failed
make: *** [src/github.com/ebay/beam/rpc/views.pb.go] Error 1
```

**Comment by ongardie** [comment]
Hi @fils, `views.proto` is included in the Beam sources. It's likely that your protoc (Protocol Buffers compiler) is out of date (check `protoc --version`). You should be able to follow the commands in https://github.com/eBay/beam/blob/master/.travis.yml to install a newer version of that.

We should probably add a note in the README and a check in the Makefile about this.

**Comment by fils** [comment]
@ongardie Thanks...
It turned out I had an old protoc in /usr/bin that was in my PATH var ahead of the new one...
it's building fine now thanks!

Looking forward to trying out a new triple store...
Thanks for going the RDF and SPARQL route.  I work a lot with W3C semantics and it's nice to have another compatible triple store to play with...       plus I like Go quite a bit too to develop in!

Thanks for the help!
