### ISSUE TITLE
run "make run" error

### ISSUE THREAD

**Issue by scienceyang** [eBay/beam#31]
run "bin/plank" shows “plank server started at localhost:20011”。However，run “make run” error：
22:23:03 txview-00 | WARN[2019-05-08 14:23:03.055084 UTC]src/github.com/ebay/beam/blog/logspecclient/client.go:222 github.com/ebay/beam/blog/logspecclient.(*Log).Read() Retrying                                      RPC=Read error="rpc error: code = Canceled desc = grpc: the client connection is closing" server="tcp://node24:20011"
22:23:03 txview-00 | INFO[2019-05-08 14:23:03.055528 UTC]src/github.com/ebay/beam/blog/logspecclient/client.go:455 github.com/ebay/beam/blog/logspecclient.(*Log).connectAnyLocked.func1() Logspec client connecting to                  server="tcp://node24:20011"
22:23:10 hashsp-00 | WARN[2019-05-08 14:23:10.884702 UTC]src/github.com/ebay/beam/blog/logspecclient/client.go:222 github.com/ebay/beam/blog/logspecclient.(*Log).Read() Retrying                                      RPC=Read error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 218.93.250.18:20011: i/o timeout\"" server="tcp://node24:20011"
22:23:10 hashsp-00 | INFO[2019-05-08 14:23:10.885279 UTC]src/github.com/ebay/beam/blog/logspecclient/client.go:455 github.com/ebay/beam/blog/logspecclient.(*Log).connectAnyLocked.func1() Logspec client connecting to                  server="tcp://node24:20011"
22:23:10 hashsp-01 | WARN[2019-05-08 14:23:10.907590 UTC]src/github.com/ebay/beam/blog/logspecclient/client.go:222 github.com/ebay/beam/blog/logspecclient.(*Log).Read() Retrying                                      RPC=Read error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 218.93.250.18:20011: i/o timeout\"" server="tcp://node24:20011"
==============================================================
How should I do

**Comment by superfell** [comment]
It seems to think your logservice is at node24. Did you by chance change the logspec address in local/config ? the default one is configured to use localhost.

**Comment by scienceyang** [comment]
I change the logspec address in local/config as hostname, but I only used one virtual machine（VMware，the network set  net model）. The virtual machine' s IP is 10.1.10.156. I don' t know where the "218.93.250.18" comes from.
Today,beam sets up normally. Changing the type of beamlog in local/config as kafka.

**Comment by superfell** [comment]
plank was only listening on localhost, so it won't be reachable via the IP/external name.
