### ISSUE TITLE
How to delete exist Beam's Disk Views before restarting the cluster

### ISSUE THREAD

**Issue by shanghai-Jerry** [eBay/beam#32]
`You'll need to clear out Beam's Disk Views' data before restarting the cluster.`

**Comment by superfell** [comment]
The default dev config places the diskviews rocksDB at $TMPDIR/rocksdb-beam-diskview-{space}-{partition}

So you can delete them all with `rm -rf $TMPDIR/rocksdb-beam-diskview*`

**Comment by shanghai-Jerry** [comment]
while i use kafka as log store, it causes ` response did not contain all the expected topic/partition blocks`

**Comment by superfell** [comment]
What version of kafka are you using? we did most of our testing with .11. If you're using something newer, then you might need a newer version of samara (the kafka client thats used) to match the kafka server version.
